<?php
// SPDX-License-Identifier: BSD-3-Clause
// TigerImage 0001 — generated images: the file on disk, and everything needed to make it again.
//
// The metadata is the point (TIGER-97). An image whose real parameters were never recorded cannot be
// iterated on, only regenerated by luck — so `params` stores what the PROVIDER actually used, not what
// the caller asked for: the size it snapped to, the seed it picked, the prompt it rewrote.
//
// `parent_id` makes a chain of refinements navigable rather than a pile of files. It is deliberately
// NOT a foreign key with a cascade: deleting a parent must not silently take its children with it, and
// an orphaned refinement is still a useful image. The service re-parents instead.
//
// `state` is the two-stage flow: `temp` is on disk and unpublished, `promoted` has a Media row, and
// the sweeper only ever touches `temp`.
return [
    'up' => [
        "CREATE TABLE IF NOT EXISTS `tigerimage_image` (
            `image_id`    CHAR(36)     NOT NULL,
            `org_id`      VARCHAR(36)  NOT NULL DEFAULT '',
            `parent_id`   CHAR(36)     NULL,
            `state`       VARCHAR(16)  NOT NULL DEFAULT 'temp',
            `disk`        VARCHAR(32)  NOT NULL DEFAULT 'local',
            `path`        VARCHAR(255) NOT NULL DEFAULT '',
            `mime`        VARCHAR(64)  NOT NULL DEFAULT 'image/png',
            `bytes`       INT UNSIGNED NOT NULL DEFAULT 0,
            `width`       INT UNSIGNED NOT NULL DEFAULT 0,
            `height`      INT UNSIGNED NOT NULL DEFAULT 0,
            `prompt`      TEXT         NULL,
            `negative`    TEXT         NULL,
            `provider`    VARCHAR(32)  NOT NULL DEFAULT '',
            `model`       VARCHAR(128) NOT NULL DEFAULT '',
            `params`      LONGTEXT     NULL,
            `cost`        DECIMAL(10,5) NULL,
            `media_id`    CHAR(36)     NULL,
            `status`      VARCHAR(20)  NOT NULL DEFAULT 'active',
            `deleted`     TINYINT(1)   NOT NULL DEFAULT 0,
            `created_by`  CHAR(36)     NULL,
            `updated_by`  CHAR(36)     NULL,
            `created_at`  DATETIME     NULL,
            `updated_at`  DATETIME     NULL,
            PRIMARY KEY (`image_id`),
            KEY `ix_ti_image_org`     (`org_id`),
            KEY `ix_ti_image_parent`  (`parent_id`),
            KEY `ix_ti_image_state`   (`state`),
            KEY `ix_ti_image_created` (`created_at`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
    'down' => [
        "DROP TABLE IF EXISTS `tigerimage_image`",
    ],
];
