<?php
// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 WebTigers. Tiger™ and WebTigers™ are trademarks of WebTigers.
/**
 * Tigerimage_Model_Image — one generated image and everything needed to make it again (TIGER-97).
 *
 * Extends Tiger_Model_Table (UUID PK + timestamps + soft-delete + standard columns).
 *
 * Every query lives here behind a NAMED finder returning a Row or Rowset — services call
 * `$model->chainFor($id)`, never a predicate they assembled themselves. That is the house rule, and
 * it is why the lineage logic below is in the model rather than smeared across the service.
 *
 * @api
 */
class Tigerimage_Model_Image extends Tiger_Model_Table
{
    protected $_name    = 'tigerimage_image';
    protected $_primary = 'image_id';

    /** On disk, unpublished. The sweeper only ever touches these. */
    const STATE_TEMP     = 'temp';
    /** Has a Media Library row. Never swept. */
    const STATE_PROMOTED = 'promoted';

    /**
     * Record a generated image.
     *
     * `params` holds what the PROVIDER actually used — the size it snapped to, the seed it chose, the
     * prompt it rewrote — not what the caller asked for. That echo is what makes a refinement
     * reproducible; without it an image can only be regenerated by luck.
     *
     * Stored as LONGTEXT rather than a JSON column: MariaDB 10.5's json_valid() CHECK rejects JSON
     * nested 32 deep and fails the whole write with a 4025, which bit this codebase before.
     *
     * @param  array $d org_id, path, mime, bytes, prompt, provider, model, params, parent_id?, …
     * @return string the new image_id
     */
    public function record(array $d)
    {
        return $this->insert([
            'org_id'    => (string) ($d['org_id'] ?? ''),
            'parent_id' => !empty($d['parent_id']) ? (string) $d['parent_id'] : null,
            'state'     => self::STATE_TEMP,
            'disk'      => (string) ($d['disk'] ?? 'local'),
            'path'      => (string) ($d['path'] ?? ''),
            'mime'      => (string) ($d['mime'] ?? 'image/png'),
            'bytes'     => (int)    ($d['bytes'] ?? 0),
            'width'     => (int)    ($d['width'] ?? 0),
            'height'    => (int)    ($d['height'] ?? 0),
            'prompt'    => (string) ($d['prompt'] ?? ''),
            'negative'  => isset($d['negative']) ? (string) $d['negative'] : null,
            'provider'  => (string) ($d['provider'] ?? ''),
            'model'     => (string) ($d['model'] ?? ''),
            'params'    => isset($d['params']) ? json_encode($d['params'], JSON_UNESCAPED_SLASHES) : null,
            'cost'      => isset($d['cost']) ? $d['cost'] : null,
        ]);
    }

    /** One image by id, scoped to an org. @return Zend_Db_Table_Row_Abstract|null */
    public function byId($imageId, $orgId = null)
    {
        $s = $this->activeSelect()->where('image_id = ?', (string) $imageId);
        if ($orgId !== null) { $s->where('org_id = ?', (string) $orgId); }
        return $this->fetchRow($s);
    }

    /** The direct refinements of an image, oldest first. @return Zend_Db_Table_Rowset_Abstract */
    public function childrenOf($imageId)
    {
        return $this->fetchAll(
            $this->activeSelect()->where('parent_id = ?', (string) $imageId)->order('created_at ASC')
        );
    }

    /**
     * The whole refinement chain an image belongs to, root first.
     *
     * Walks up to the root then back down, rather than a recursive CTE: MySQL 5.7 and MariaDB 10.1 are
     * both in Tiger's supported range on shared hosting and neither has them. Depth is bounded so a
     * cycle — which a re-parent bug could create — terminates instead of hanging the request.
     *
     * @param  string $imageId
     * @param  int    $maxDepth
     * @return array<int,Zend_Db_Table_Row_Abstract> root first
     */
    public function chainFor($imageId, $maxDepth = 64)
    {
        $row = $this->byId($imageId);
        if (!$row) { return []; }

        $up   = [$row];
        $seen = [(string) $row->image_id => true];
        while (count($up) < $maxDepth && !empty($row->parent_id)) {
            $parent = $this->byId($row->parent_id);
            if (!$parent || isset($seen[(string) $parent->image_id])) { break; }
            $seen[(string) $parent->image_id] = true;
            array_unshift($up, $parent);
            $row = $parent;
        }
        return $up;
    }

    /**
     * Temp images older than a cutoff — the sweeper's input.
     *
     * PROMOTED IMAGES ARE NEVER RETURNED. Promotion is the user saying "keep this", and a retention
     * sweep must not overrule that.
     *
     * @param  string $cutoff 'Y-m-d H:i:s'
     * @param  int    $limit  bounded so one sweep cannot run unboundedly long
     * @return Zend_Db_Table_Rowset_Abstract
     */
    public function tempOlderThan($cutoff, $limit = 200)
    {
        return $this->fetchAll(
            $this->activeSelect()
                 ->where('state = ?', self::STATE_TEMP)
                 ->where('created_at < ?', (string) $cutoff)
                 ->order('created_at ASC')
                 ->limit((int) $limit)
        );
    }

    /** Recent images for an org, newest first — the studio grid. @return Zend_Db_Table_Rowset_Abstract */
    public function recentForOrg($orgId, $limit = 60)
    {
        return $this->fetchAll(
            $this->activeSelect()
                 ->where('org_id = ?', (string) $orgId)
                 ->order('created_at DESC')
                 ->limit((int) $limit)
        );
    }

    /**
     * Re-parent an image's children onto its own parent, so deleting a middle link does not orphan
     * the refinements below it. A root's children become roots.
     *
     * @param  Zend_Db_Table_Row_Abstract $row the image being removed
     * @return int how many children moved
     */
    public function reparentChildren($row)
    {
        $newParent = !empty($row->parent_id) ? (string) $row->parent_id : null;
        $moved     = 0;
        foreach ($this->childrenOf($row->image_id) as $child) {
            $child->parent_id = $newParent;
            $child->save();          // save() keeps Tiger_Model_Table's stamping
            $moved++;
        }
        return $moved;
    }


    /**
     * Total estimated spend for an org since a cutoff (TIGER-100).
     *
     * Counts DELETED rows too — binning an image does not refund it. A sum that fell when a user
     * tidied up would let a loop reset its own budget by discarding as it went.
     *
     * @param  string $orgId
     * @param  string $since 'Y-m-d H:i:s'
     * @return float USD
     */
    public function spentSince($orgId, $since)
    {
        $row = $this->fetchRow(
            $this->select()->from($this->_name, ['total' => 'COALESCE(SUM(cost), 0)'])
                 ->where('org_id = ?', (string) $orgId)
                 ->where('created_at >= ?', (string) $since)
        );
        return $row ? (float) $row->total : 0.0;
    }

    /** Decode the stored params blob. @return array */
    public function paramsOf($row)
    {
        if (!$row || empty($row->params)) { return []; }
        $d = json_decode((string) $row->params, true);
        return is_array($d) ? $d : [];
    }
}
